### ISSUE TITLE
3D object detection code of TokenFusion

### ISSUE THREAD

**Issue by ZJU-PLP** [yikaiw/TokenFusion#2]
@yikaiw  Hi, Dr. Wang. 
Thanks for sharing so nice work **TokenFusion**. However, I cannot find the code of **3D object detection** by your TokenFusion repository. I want to know whether you will release this part code(i.e., 3D object detection) ?

**Comment by yikaiw** [comment]
Yes, I'm preparing the code for fusing vision and point cloud, and this part of the code will be released.

**Comment by yikaiw** [comment]
Bust at other things these days. I will hurry up.

**Comment by yikaiw** [comment]
Hi, please see https://github.com/yikaiw/TokenFusion/tree/main/object-detection-3d, still improving. Thanks for your attention.

**Comment by ZJU-PLP** [comment]
@yikaiw Hi, yikai.
I get the error "TypeError: __init__() got an unexpected keyword argument 'data_root'" when run the bash `CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --master_port 2229 --nproc_per_node 4 train_dist.py --max_epoch 600 --val_freq 25 --save_freq 25 --lr_decay_epochs 420 480 540 --num_point 20000 --num_decoder_layers 6 --size_cls_agnostic --size_delta 0.0625 --heading_delta 0.04 --center_delta 0.1111111111111 --weight_decay 0.00000001 --query_points_generator_loss_coef 0.2 --obj_loss_coef 0.4 --dataset sunrgbd --data_root . --use_img --log_dir log/exp_name
`

The SUN RGB-D dataset is already prepared. I change the --data_root  to ./sunrgbd and cannot fix the problem.
![image](https://user-images.githubusercontent.com/32757213/179963389-a565f92f-654d-4fd9-84fe-a64d5bde0b67.png)

**Comment by yikaiw** [comment]
Hi, it seems that the error is not due to the format of data path. Could you tell me which line raises the error "TypeError: init() got an unexpected keyword argument 'data_root'"?

**Comment by ZJU-PLP** [comment]
@yikaiw Hi, the error is showed as follow:
![image](https://user-images.githubusercontent.com/32757213/180722263-42b2e470-57a1-4d6f-964d-3589ad448b02.png)

**Comment by wf-hahaha** [comment]
@yikaiw Thank you very much for sharing this work. About 3D object detection, could you share the trained weights and demo

**Comment by yikaiw** [comment]
Sorry, the repo is not able to be maintained after graduation/internship. Suggestion: please also consider https://github.com/haoy945/DeMF which achieves new SOTA according to https://paperswithcode.com/sota/3d-object-detection-on-sun-rgbd-val.
