### ISSUE TITLE
SUN RGB-D dataset results

### ISSUE THREAD

**Issue by LifeBeyondExpectations** [yikaiw/TokenFusion#4]
Are you planning to update the training details of SUN RGBD dataset for the semantic segmentation task?

**Comment by yikaiw** [comment]
Sorry, the repo is not being maintained after graduation. Please kindly refer to this implementation on the NYUdv2 dataset.

**Comment by yikaiw** [comment]
Sorry, the repo is not able to be maintained after graduation/internship. Please refer to this implementation on the NYUdv2 dataset.
